Fix error in Commerce 1.3, min compatibility to be bumped to 1.3.0-dev7
Fatal error: Declaration of modmore\Commerce_SnippetStatusAction\Validation\SnippetWithNameExists::isValid($value) must be compatible with modmore\Commerce\Admin\Widgets\Form\Validation\Rule::isValid($value, ?modmore\Commerce\Services\I18n $i18n = null, ?array $translations = [])